name: fistikpazar
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  mailjet: ^1.0.4+4
  sexy_api_client: ^0.0.6+6
  http: ^1.2.1
  flutter_svg: ^2.0.9
  data_filters: ^1.0.2
  image_picker: ^1.1.2
  curved_navigation_bar: ^1.0.3
  fl_chart: ^0.68.0
  provider: ^6.1.2
  intl: ^0.18.1
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^4.2.1
  dio: ^5.4.3+1
  flutter_localization: ^0.2.0
  collection: ^1.18.0
  http_parser: ^4.0.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - icons/

  # Localizations
  generate: true
  # Eklediğiniz diğer localizations desteklerini buraya ekleyin.
